### ISSUE TITLE
Client maken die de webserver aanspreekt

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/MindstormR#5]
Client maken (web applicatie in MVC) die de (remote) webserver aanspreekt en zo de robot kan besturen. Dit wordt een soort showcase voor wat de API allemaal kan. Het is de bedoeling dat hiermee de robot op afstand bestuurd kan worden.
- [x] ASP.NET MVC (basic, zonder authenticatie) project toevoegen aan de MindstormR solution - #9 
- [x] UI maken met controls om de robot te besturen - #11
- [x] Webservice implementeren in de client applicatie - #10

**Comment by henkmollema** [comment]
Besproken dat we de voorkant in ASP.NET MVC maken.
